- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlDataTypeSpec.java
- server/src/main/java/org/apache/calcite/sql/ddl/SqlColumnDeclaration.java
Reverts googleinterns/calcite#19
> Revert "[CALCITE] Added support for UPPERCASE and CASESPECIFIC column level attributes for CREATE TABLE expression"

- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlOrderBy.java
- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
> [CALCITE] Unparse SqlOrderBy with dialect support

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlCreateTable.java
- babel/src/main/java/org/apache/calcite/sql/babel/Volatility.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
[CALCITE] Add temp keyword support in table creation
> [CALCITE] Add temp keyword support in table creation

- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlBetweenOperator.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorUtil.java
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
[CALCITE] Fix nested schema type checking and BETWEEN unparsing
> [CALCITE] Fix nested schema type checking and BETWEEN unparsing

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlCreateTable.java
- babel/src/main/java/org/apache/calcite/sql/babel/WithDataType.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
[CALCITE] Add support for CREATE TABLE .. WITH NO DATA.
> [CALCITE] Add support for CREATE TABLE .. WITH NO DATA.

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlCreateAttributeMap.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
[CALCITE] Add support for CREATE TABLE map option
> [CALCITE] Add support for CREATE TABLE map option

- babel/src/main/java/org/apache/calcite/sql/babel/SqlIndex.java
- babel/src/main/java/org/apache/calcite/sql/babel/SqlPrimaryIndex.java
- core/src/main/java/org/apache/calcite/sql/SqlColumnAttribute.java
- core/src/main/java/org/apache/calcite/sql/SqlDataTypeSpec.java
- core/src/main/java/org/apache/calcite/sql/SqlSelect.java
- server/src/main/java/org/apache/calcite/sql/ddl/SqlColumnDeclaration.java
Also fixes a operands ordering bug in SqlSelect.
> [CALCITE] Small fixes to linter warnings

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlColumnAttributeCaseSpecific.java
- core/src/main/java/org/apache/calcite/sql/SqlColumnAttributeCompress.java
[CALCITE] Add support for COMPRESS phrase in CREATE TABLE
> [CALCITE] Add support for COMPRESS phrase in CREATE TABLE

- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlColumnAttributeCompress.java
[CALCITE] Add support for COMPRESS phrase with values in CREATE TABLE
> [CALCITE] Add support for COMPRESS phrase with values in CREATE TABLE

- server/src/main/codegen/includes/parserImpls.ftl
- server/src/test/java/org/apache/calcite/test/ServerParserTest.java
[CALCITE] Allow compound identifiers in REPLACE VIEW
> [CALCITE] Allow compound identifiers in REPLACE VIEW

- babel/build.gradle.kts
- buildSrc/settings.gradle.kts
- buildSrc/subprojects/parser/src/main/kotlin/org/apache/calcite/buildtools/parser/DialectGenerateTask.kt
Tests will be added in a future PR as they will test the script as a whole, not each individual function.
> [CALCITE] Gradle task: Extraction of functions

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlExecMacro.java
- babel/src/main/java/org/apache/calcite/sql/babel/SqlExecMacroParam.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
Add support to the optional parameter list in Exec Macro statements.
> [CALCITE] Exec macro param list

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlAlterTableRename.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
Added support for ALTER RENAME such as "ALTER TABLE foo RENAME bar TO baz".
> [CALCITE] Added support for ALTER RENAME.

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlAlterTableDrop.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
Added support for queries of the form:
ALTER TABLE foo DROP bar [IDENTITY]
> [CALCITE] Added support for ALTER DROP.

- babel/src/main/java/org/apache/calcite/sql/babel/SqlAlterTableAddColumns.java
- babel/src/main/java/org/apache/calcite/sql/babel/SqlAlterTableAttributeChecksum.java
- babel/src/main/java/org/apache/calcite/sql/babel/SqlAlterTableAttributeDataBlockSize.java
- babel/src/main/java/org/apache/calcite/sql/babel/SqlAlterTableAttributeFreeSpace.java
- babel/src/main/java/org/apache/calcite/sql/babel/SqlTableAttribute.java
> [CALCITE] Add @Override tag and repalce SqlAlterTableAddColumns assert with comment

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/codegen/config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/test/codegen/config.fmpp
- server/src/main/codegen/config.fmpp
[CALCITE] Allow NAMED expression to work with literals and identifiers
> [CALCITE] Allow NAMED expression to work with literals and identifiers

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlTimeFunction.java
[CALCITE] Add support for TIME as a function
> [CALCITE] Add support for TIME as a function

- core/src/main/codegen/config.fmpp
- core/src/main/java/org/apache/calcite/sql/SqlExcept.java
- core/src/main/java/org/apache/calcite/sql/SqlSelect.java
- core/src/main/java/org/apache/calcite/sql/SqlSelectOperator.java
- parsing/dialects/bigquery/config.fmpp
- parsing/dialects/bigquery/parserImpls.ftl
- parsing/dialects/bigquery/src/test/java/org/apache/calcite/test/BigQueryParserTest.java
- parsing/dialects/defaultdialect/config.fmpp
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/hive/config.fmpp
- parsing/dialects/mysql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/postgresql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/redshift/config.fmpp
- parsing/src/main/resources/Parser.jj
- Added java class SqlExcept
- Added parsing logic to BigQuery's parserImpls.ftl
- reordered imports in BigQuery's config.fmpp to be alphabetical
- Added new tests
> [CALCITE] New node type for EXCEPT in SELECT

- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
Added support for queries like
ALTER TABLE foo.bar (...)
> [CALCITE] Added support for compound identifiers in ALTER TABLE.

- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/src/main/resources/Parser.jj
[CALCITE] Let MERGE INTO ... WHEN NOT MATCHED accept compound identifiers
> [CALCITE] Let MERGE INTO ... WHEN NOT MATCHED accept compound identifiers

- core/src/main/codegen/config.fmpp
- parsing/dialects/bigquery/config.fmpp
- parsing/dialects/defaultdialect/config.fmpp
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/dialects/hive/config.fmpp
- parsing/dialects/mysql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/postgresql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/redshift/config.fmpp
- parsing/src/main/resources/Parser.jj
[CALCITE] Allow optional FROM keyword in DELETE statement
> [CALCITE] Allow optional FROM keyword in DELETE statement

- core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java
- core/src/main/java/org/apache/calcite/sql/pretty/SqlPrettyWriter.java
- added @Override tag to a function
- converted an assert() to a if-check
- expanded cases of a few switch statements
- removed a SqlPrettyWriter constructor with an unused argument
> [CALCITE] Small linter fixes

- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
[CALCITE] Remove bq interval validation since interval can contain expressions
> [CALCITE] Remove bq interval validation since interval can contain expressions

- core/src/main/java/org/apache/calcite/sql/SqlSelect.java
- parsing/intermediate/dialects/bigquery/parserImpls.ftl
[CALCITE] Convert except expression to more explicit SqlExcept type
> [CALCITE] Convert except expression to more explicit SqlExcept type

- core/src/main/java/org/apache/calcite/rel/type/UnknownRecordType.java
- core/src/main/java/org/apache/calcite/sql/validate/DelegatingScope.java
- core/src/main/java/org/apache/calcite/sql/validate/IdentifierNamespace.java
- core/src/main/java/org/apache/calcite/sql/validate/ListScope.java
- core/src/main/java/org/apache/calcite/sql/validate/MatchRecognizeScope.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/sql/test/SqlTestFactory.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorBestEffortTest.java
Added support for handling unknown table identifiers and columns deriving from unknown tables.
> [CALCITE] Best effort validation.

- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/DialectGenerate.java
- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/ExtractedData.java
- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/Keyword.java
- buildSrc/subprojects/parser/src/test/java/org/apache/calcite/test/DialectGenerateTest.java
- buildSrc/subprojects/parser/src/test/java/org/apache/calcite/test/KeywordTest.java
There are a lot of changes so I decided to split it up into multiple PRs. This one contains:
- The processKeywords() method + tests 
- The new Keyword class + tests
- The unparseReservedKeywords() method + tests
> [CALCITE] First part of Keywords Refactor

- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/src/main/resources/Parser.jj
- parsing/src/test/java/org/apache/calcite/test/SqlDialectParserTest.java
[CALCITE] Allow '#' and '$' tokens in identifiers
> [CALCITE] Allow '#' and '$' tokens in identifiers

- core/src/main/java/org/apache/calcite/sql/SqlColumnAttribute.java
- core/src/main/java/org/apache/calcite/sql/util/SqlBasicVisitor.java
- core/src/main/java/org/apache/calcite/sql/util/SqlShuttle.java
- core/src/main/java/org/apache/calcite/sql/util/SqlVisitor.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
[CALCITE] Add validation support for SqlColumnAttribute nodes
> [CALCITE] Add validation support for SqlColumnAttribute nodes

- core/src/main/java/org/apache/calcite/sql/SqlDelete.java
- parsing/dialects/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
Added support for queries of the form DELETE <delete_table_name> [FROM] table
> [CALCITE] DELETE with delete_table_name

- core/src/main/java/org/apache/calcite/sql/SqlExcept.java
- parsing/dialects/intermediate/dialects/bigquery/parserImpls.ftl
- parsing/dialects/intermediate/dialects/bigquery/src/test/java/org/apache/calcite/test/BigQueryParserTest.java
- Removed overriding of SqlSelect in BigQuery
- Override SelectExpression() in BigQuery
> [CALCITE] Fixed EXCEPT unparsing bug

- parsing/dialects/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
[CALCITE] Allow optional IS prefix to IN operator
> [CALCITE] Allow optional IS prefix to IN operator
