googleinterns/calcite

- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
[CALCITE] Update INSERT INTO statement to handle SELECT statements that are in parentheses.
An example query that this would handle is:
insert into foo (a, b) (SELECT * FROM bar)
> [CALCITE] Update INSERT INTO statement to handle SELECT statements that are in parentheses.

- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlUpdate.java
- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Big Query wants statements like `update abc from def set abc.x = def.y, abc.z = def.k;` to be unparsed as `update abc set abc.x = def.y, abc.z = def.k from def;`
> [CALCITE] Modify unparsing order of UPDATE statement for BIG QUERY dialect

- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
[CALCITE] Unparse unicode correctly in BigQuery
BQ doesn't support u& unicode literals, but it does support \uXXXX type characters, change to unparse in this way
> [CALCITE] Unparse unicode correctly in BigQuery

- babel/src/main/codegen/config.fmpp
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
[CALCITE] Omit backticks when unparsing IF keyword in BigQuery SQL dialect.
> [CALCITE] Omit backticks when unparsing IF keyword in BigQuery SQL dialect.

- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlMerge.java
- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
**Original Big Query unparsing:** 
```
MERGE INTO T1 AS A
USING T2 AS B
ON A.X = B.X
WHEN MATCHED THEN UPDATE SET
Y = B.Y
WHEN NOT MATCHED THEN INSERT (X, Y) (VALUES  (B.X, B.Y))
```
**New Big Query unparsing:**
```
MERGE INTO T1 AS A
USING T2 AS B
ON A.X = B.X
WHEN MATCHED THEN UPDATE SET
Y = B.Y
WHEN NOT MATCHED THEN INSERT (X, Y) VALUES  (B.X, B.Y)
```
> [CALCITE] Fixed MERGE INTO with INSERT statement unparsing in Big Query

- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
[CALCITE] Allow indices to be optionally separated by commas
> [CALCITE] Allow indices to be optionally separated by commas

- server/src/main/codegen/config.fmpp
- server/src/test/java/org/apache/calcite/test/ServerParserTest.java
[CALCITE] Add abbreviated keywords to server module
This add supports for the following abbreviations in the server module:
- DEL (aka DELETE)
- INS (aka INSERT)
- SEL (aka SELECT)
- UPD (aka UPDATE)
> [CALCITE] Add abbreviated keywords to server module

- babel/src/main/codegen/config.fmpp
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/codegen/config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/test/codegen/config.fmpp
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
- server/src/main/codegen/config.fmpp
[CALCITE] Add support for colon separator in compound identifiers
This change also modifies the way JSON names are extracted because the previous logic erroneously used the Expression() parsing function to extract only a string literal or an identifier. This did not work once <COLON> was added as an allowed part of a compound identifier for an input key/value pair. For example, "foo: bar".
> [CALCITE] Add support for colon separator in compound identifiers

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/codegen/config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlFormatFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- core/src/test/codegen/config.fmpp
- server/src/main/codegen/config.fmpp
This change also restructures the alternative type casting parsing
logic, while keeping the behavior the same.
> [CALCITE] Add support for inline FORMAT clause

- core/src/main/codegen/templates/Parser.jj
- site/_docs/reference.md
This change also adds FORMAT to a list of functions in reference.md to
ignore.
> [CALCITE] Allow numeric literals in JSON names

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/codegen/config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/test/codegen/config.fmpp
- server/src/main/codegen/config.fmpp
Added support for omitted values in an INSERT statement:
`INSERT INTO <table_name> [VALUES] \(<value>?(,<value>?)*\);`
> [CALCITE] Added support for INSERT with omitted values

- babel/src/main/codegen/config.fmpp
- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/main/java/org/apache/calcite/sql/babel/SqlHostVariable.java
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
- core/src/main/codegen/config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/test/codegen/config.fmpp
- server/src/main/codegen/config.fmpp
Host variables are variables prefixed with a colon (`:variableName`)
> [CALCITE] Added support for host variables

- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/DialectGenerate.java
- buildSrc/subprojects/parser/src/test/java/org/apache/calcite/test/DialectGenerateTest.java
- buildSrc/subprojects/parser/src/test/resources/processFileTests/angle_brackets/angle_brackets.txt
- buildSrc/subprojects/parser/src/test/resources/processFileTests/angle_brackets/angle_brackets_expected.txt
- Added parsing support for types that contain angle brackets
- Made function name regex more robust
- Made getFunctionName() public and added tests
> [CALCITE] DialectGenerate now parses types that contain angle brackets.

- babel/src/main/codegen/includes/parserImpls.ftl
- babel/src/test/java/org/apache/calcite/test/BabelParserTest.java
[CALCITE] Allow CompoundIdentifier in FORMAT, NAMED, and alternative casts
> [CALCITE] Allow CompoundIdentifier in FORMAT, NAMED, and alternative casts

- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/DialectGenerate.java
- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/DialectTraverser.java
- Removed duplicate imports
- Reordered imports to be alphabetical
- converted "static final" fields to be upper snakecase
> [CALCITE] Fixed linter errors in DialectGenerate and DialectTraverser

- core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java
- core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
VARBYTE syntax: `VARBYTE\(n\)`
BYTE syntax: `BYTE[\(n\)]`
> [CALCITE] Add support for VARBYTE and BYTE data types

- core/src/main/codegen/config.fmpp
- core/src/main/java/org/apache/calcite/sql/SqlHexCharStringLiteral.java
- parsing/dialects/bigquery/config.fmpp
- parsing/dialects/defaultdialect/config.fmpp
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/dialects/hive/config.fmpp
- parsing/dialects/mysql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/postgresql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/redshift/config.fmpp
- parsing/src/main/resources/Parser.jj
Add the ability to parse a hex character format string literal.
> [CALCITE] Hex Character String Literal Rework

- core/src/main/java/org/apache/calcite/sql/SqlCaseSpecific.java
- core/src/main/java/org/apache/calcite/sql/SqlInlineCaseSpecific.java
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- Added java class for unparsing
- Added two functions for parsing in dialect1's parserImpls (can't combine them due to lookahead issues)
- Added tests for dialect1
> [CALCITE] Add support for inline CASESPECIFIC

- core/src/main/codegen/config.fmpp
- parsing/dialects/bigquery/config.fmpp
- parsing/dialects/defaultdialect/config.fmpp
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/dialects/hive/config.fmpp
- parsing/dialects/mysql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/postgresql/config.fmpp
- parsing/dialects/postgresqlBase/dialects/redshift/config.fmpp
- parsing/src/main/resources/Parser.jj
This adds support for functions not wrapped in outer parentheses
> [CALCITE] Support functions in alternative CAST, inline FORMAT, and NAMED expression

- core/src/main/java/org/apache/calcite/sql/SqlJsonTypeNameSpec.java
We can't test this function so we decided to just have it return false.
> [CALCITE] Made equalsDeep function of SqlJsonTypeNameSpec return false

- core/src/main/java/org/apache/calcite/sql/SqlPeriodTypeNameSpec.java
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
By adding a SqlNameSpec type class, now user can define type to be a period type.
> [CALCITE] Add support for Sql PERIOD type

- core/src/main/java/org/apache/calcite/sql/SqlColumnAttributeCompress.java
- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- COMPRESS can now be specified on a constant without parentheses but still supports a list
- Refactored SqlColumnAttributeCompress to allow for a single value or a list of values
- Added new tests
> [CALCITE] Rework of CREATE TABLE COMPRESS attribute

- core/src/main/java/org/apache/calcite/sql/SqlClobTypeNameSpec.java
Otherwise, we receive linter errors that this is not an exhaustive switch/case across all CharacterSet enum values.
> [CALCITE] Update SqlClobTypeNameSpec's isValidMaxLength() switch/case

- core/src/main/java/org/apache/calcite/sql/SqlBlobTypeNameSpec.java
- core/src/main/java/org/apache/calcite/sql/SqlClobTypeNameSpec.java
- core/src/main/java/org/apache/calcite/sql/SqlColumnAttributeCompress.java
- core/src/main/java/org/apache/calcite/sql/SqlPeriodTypeNameSpec.java
- removed occurrences of sep() calls during unparsing that were not within an outer frame
- removed call to toString() on an enum where not required
- modified SqlColumnAttributeCompress's value field to be public
- changed formatting in TimeScale enum
> [CALCITE] Small fixes to formatting, field visibility, and using sep() during unparsing

- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
[CALCITE] Update inline MOD operator to handle compound identifiers
> [CALCITE] Update inline MOD operator to handle compound identifiers

- core/src/main/java/org/apache/calcite/sql/SqlCreateMacro.java
- core/src/main/java/org/apache/calcite/sql/SqlInsert.java
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- core/src/main/java/org/apache/calcite/sql/SqlWriter.java
- core/src/main/java/org/apache/calcite/sql/pretty/SqlPrettyWriter.java
- parsing/dialects/dialect1/config.fmpp
- parsing/dialects/dialect1/parserImpls.ftl
- parsing/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/src/main/resources/Parser.jj
- Added new CREATE_MACRO frame type to ensure that SELECT statements in the body aren't unparsed with parens
- Added new AST node SqlCreateMacro and corresponding parsing logic
- Fixed bug where SELECT list created in SqlInsert was never closed
> [CALCITE] Added support for CREATE/REPLACE MACRO statements

- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/DialectGenerate.java
- buildSrc/subprojects/parser/src/test/java/org/apache/calcite/test/DialectGenerateTest.java
- buildSrc/subprojects/parser/src/test/resources/processFileTests/multiple_functions_separated/multiple_functions_separated.txt
- buildSrc/subprojects/parser/src/test/resources/processFileTests/multiple_functions_separated/multiple_functions_separated_expected.txt
Required to handle this [use case](https://github.com/googleinterns/calcite/blob/916228a2fda68521c16e564f4deaaa42b147fba8/parsing/src/main/resources/Parser.jj#L1430).
> [CALCITE] DialectGenerate can now parse function with types that contain periods

- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/CurlyParser.java
- buildSrc/subprojects/parser/src/test/java/org/apache/calcite/test/CurlyParserTest.java
- buildSrc/subprojects/parser/src/test/resources/processFileTests/multiple_functions_separated/multiple_functions_separated.txt
- buildSrc/subprojects/parser/src/test/resources/processFileTests/multiple_functions_separated/multiple_functions_separated_expected.txt
A bug was introduced in https://github.com/googleinterns/calcite/pull/198 which prevented escaped backslashes from being parsed within double quotes.
> [CALCITE] Fixed bug where CurlyParser would not parse escaped backslashes in a string

- core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Fixed bug which rewrites 
SELECT -2 + CURRENT_DATE()
to 
SELECT INTERVAL -'-2' DAY + CURRENT_DATE
(with a double negative sign).
The query should now be rewritten to
SELECT INTERVAL -'2' DAY + CURRENT_DATE
With only a single negative sign outside of the quoted string.
> [CALCITE] Fixed redundant negative in integer-to-interval coercion.

- parsing/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
Added support for expressions in inline MOD operator using a setup similar to [AlternativeTypeConversionQuery()](https://github.com/googleinterns/calcite/blob/master/parsing/intermediate/dialects/dialect1/parserImpls.ftl#L4055).
> [CALCITE] Added support for expressions in inline MOD operator

- buildSrc/subprojects/parser/src/main/java/org/apache/calcite/buildtools/parser/Keyword.java
The instanceof operator should automatically handle the null check. Also, the keyword.equals() below should cover the (this == obj) equality check.
> [CALCITE] Update Keyword custom equals logic

- core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/util/TestUtil.java
- linq4j/src/test/java/org/apache/calcite/linq4j/test/Linq4jTest.java
Fixes unit tests that are currently failing on Cloudtop environment due to faulty assumptions.
> [CALCITE] Make Calcite unit tests compatible with Google's Java version

- parsing/dialects/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- BinaryRowOperator overridden in Dialect1
- Added support for caret negation operator "^" before` =, <, >, <=, >=, LIKE, IN`.
- Added support for NOT before `=, <, >, <=, >=`
- Unparses to equivalent existing operator
> [CALCITE] Extended caret negation and NOT support before operators

- core/src/main/java/org/apache/calcite/sql/validate/DelegatingScope.java
- core/src/main/java/org/apache/calcite/sql/validate/ListScope.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorBestEffortTest.java
Modifies column resolution for unknown columns, so that unknown columns are not attributed to arbitrary unknown tables.
> [CALCITE] Handle ambiguous column resolution for unknown tables.

- core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
- core/src/main/java/org/apache/calcite/sql/SqlDelete.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java
- parsing/dialects/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/parserImpls.ftl
This adds support for the following syntax to Dialect1:
DELETE <delete_table_name> <table_name> FROM <table_name> [AS <alias>] (, <table_name> [AS <alias>])*;
> [CALCITE] DELETE join condition form

- core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlUpdate.java
- core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
- parsing/dialects/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/parserImpls.ftl
When this feature was first added it was overlooked that TableRef() can also parse aliases.
> [CALCITE] Replaced calls of SourceTableAndAlias() to TableRef()

- core/src/test/java/org/apache/calcite/sql/test/SqlTestFactory.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- parsing/dialects/intermediate/dialects/defaultdialect/src/test/java/org/apache/calcite/test/DefaultDialectValidatorTest.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
- parsing/dialects/intermediate/dialects/mysql/src/test/java/org/apache/calcite/test/MySQLValidatorTest.java
There were a 11 tests in SqlValidatorTest that failed when executed using the Dialect1 parser. I moved most of these to DefaultDialectValidatorTest with the exception of 1 that was MySQL specific which I moved to MySQLValidatorTest.
The @LocaleEnUs annotation was removed because it didn't seem to serve much of a purpose and was throwing an initilizationError when I tried to extend SqlValidatorTest.
> [CALCITE] Validation: Allow unit tests to specify parser

- parsing/dialects/intermediate/dialects/dialect1/parserImpls.ftl
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ParserTest.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
Updated the Dialect1 parsing logic to use the SqlStdOperatorTable.MOD built-in function. Also, fixed a bug when an expression was used in the second argument to the MOD operator.
> [CALCITE] Fix inline MOD validation on subqueries

- core/src/main/java/org/apache/calcite/schema/impl/ExplicitRowTypeTable.java
- core/src/main/java/org/apache/calcite/sql/SqlCreateTable.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
- Created new class ExplicitRowTypeTable that extends from Table
- Add validation logic to SqlCreateTable that creates an instance of ExplicitRowTypeTable and adds it to the schema
- Added tests
> [CALCITE] Extract schema for CREATE TABLE statements

- core/src/main/java/org/apache/calcite/schema/impl/UnknownPlaceholderTable.java
- core/src/main/java/org/apache/calcite/sql/validate/IdentifierNamespace.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorBestEffortTest.java
When tables are specified via compound identifiers like foo.bar, this will now result in prefixes getting added as subschemas to the root schema, and tables getting added to the appropriate subschemas (ex. "foo" will be added as a subschema to the root, and "bar" will be added as a table to subschema "foo").
> [CALCITE] Unknown compound identifiers

- core/src/main/java/org/apache/calcite/sql/SqlSignal.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
Also temporarily modifies the testCreateProcedureMerge() unit test to workaround a bug that may have been introduced by https://github.com/googleinterns/calcite/pull/323/
> [CALCITE] Handle resignal validation scenario

- core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
Some cast calls only have a SqlColumnAttribute as the second operand. In that case, it should return the data type of the first operand.
> [CALCITE] Handle validation of CAST calls without a data type

- core/src/main/java/org/apache/calcite/sql/validate/IdentifierNamespace.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorBestEffortTest.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
Previously, unknown tables and subschemas were being attached directly to the root schema - this is not always the correct behavior, so this functionality has been removed.
> [CALCITE] Fix: Rollback schema construction for unknown tables.

- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
- core/src/main/java/org/apache/calcite/sql/type/BasicSqlType.java
- core/src/main/java/org/apache/calcite/sql/validate/DelegatingScope.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorBestEffortTest.java
- parsing/dialects/intermediate/dialects/dialect1/src/test/java/org/apache/calcite/test/Dialect1ValidatorTest.java
Columns deriving from unknown subqueries no longer be rewritten with the ** prefix.
> [CALCITE] Fix column expansion from unknown subqueries (remove ** suffix)

- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Currently, queries like
SELECT rank() from emp
will fail (because you need an OVER clause), but aliased queries like
SELECT rank() as r from emp
will not. The query is semantically identical, so this fix ensures that the query will fail in either case.
> [CALCITE] Ensured invalid rank() call still fails even when aliased.
